KerasJson: muon/model_2GeV.10.json
KerasH5:   muon/model_weights_2GeV.10.h5
OutputDir: my-hls-test-muon
ProjectName: myproject
XilinxPart: xc7vx690tffg1927-2
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 2
DefaultPrecision: ap_fixed<18,8> 
